# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNFgjU69K1sAT43dF0J_dn80mlVan9oE
"""


import pandas as pd
import numpy as np

# 1. Upload the file
from google.colab import files
uploaded = files.upload()

df = pd.read_excel('financials.xlsx', sheet_name='Sheet1')

df.columns = ['Company', 'FY_End_Date', 'Fiscal_Year', 'Total_Revenue',
              'Net_Income', 'Total_Assets', 'Total_Liabilities', 'Cash_Flow_Ops']

# Year-over-Year Growth
for col in ['Total_Revenue', 'Net_Income', 'Cash_Flow_Ops']:
    df[f'{col}_YoY_%'] = df.groupby('Company')[col].pct_change() * 100

# Profitability Ratios
df['Net_Margin_%'] = (df['Net_Income'] / df['Total_Revenue']) * 100
df['ROA_%'] = (df['Net_Income'] / df['Total_Assets']) * 100

# Display clean results
result = df[['Company', 'Fiscal_Year', 'Total_Revenue', 'Net_Income',
             'Net_Margin_%', 'ROA_%', 'Cash_Flow_Ops', 'Cash_Flow_Ops_YoY_%']].round(2)

print(result)

def simple_chatbot(user_query):
    query = user_query.strip().lower()

    # Query 1: Total Revenue (latest year per company)
    if "total revenue" in query and "microsoft" in query:
        val = df[(df['Company'] == 'Microsoft') & (df['Fiscal_Year'] == 'FY2025')]['Total_Revenue'].iloc[0]
        return f"Microsoft's total revenue in FY2025 is ${val:,} million."

    elif "total revenue" in query and "tesla" in query:
        val = df[(df['Company'] == 'Tesla') & (df['Fiscal_Year'] == 'FY2024')]['Total_Revenue'].iloc[0]
        return f"Tesla's total revenue in FY2024 is ${val:,} million."

    elif "total revenue" in query and "apple" in query:
        val = df[(df['Company'] == 'Apple') & (df['Fiscal_Year'] == 'FY2024')]['Total_Revenue'].iloc[0]
        return f"Apple's total revenue in FY2024 is ${val:,} million."

# Predefined Responses
def simple_chatbot(user_query):
    query = user_query.strip().lower()

    # Query 1: Total Revenue (latest year per company)
    if "total revenue" in query and "microsoft" in query:
        val = df[(df['Company'] == 'Microsoft') & (df['Fiscal_Year'] == 'FY2025')]['Total_Revenue'].iloc[0]
        return f"Microsoft's total revenue in FY2025 is ${val:,} million."

    elif "total revenue" in query and "tesla" in query:
        val = df[(df['Company'] == 'Tesla') & (df['Fiscal_Year'] == 'FY2024')]['Total_Revenue'].iloc[0]
        return f"Tesla's total revenue in FY2024 is ${val:,} million."

    elif "total revenue" in query and "apple" in query:
        val = df[(df['Company'] == 'Apple') & (df['Fiscal_Year'] == 'FY2024')]['Total_Revenue'].iloc[0]
        return f"Apple's total revenue in FY2024 is ${val:,} million."

    # Query 2: Net Income YoY Change
    elif "net income" in query and "changed" in query and "microsoft" in query:
        latest, prev = get_yoy('Microsoft', 'Net_Income')
        change = latest - prev
        pct = (change / prev) * 100
        direction = "increased" if change > 0 else "decreased"
        return f"Microsoft's net income {direction} from ${prev:,}M to ${latest:,}M (+{pct:.1f}%) in FY2025."

    elif "net income" in query and "changed" in query and "tesla" in query:
        latest, prev = get_yoy('Tesla', 'Net_Income')
        change = latest - prev
        pct = (change / prev) * 100
        direction = "increased" if change > 0 else "decreased"
        return f"Tesla's net income {direction} from ${prev:,}M to ${latest:,}M ({pct:+.1f}%) in FY2024."

    elif "net income" in query and "changed" in query and "apple" in query:
        latest, prev = get_yoy('Apple', 'Net_Income')
        change = latest - prev
        pct = (change / prev) * 100
        direction = "increased" if change > 0 else "decreased"
        return f"Apple's net income {direction} from ${prev:,}M to ${latest:,}M ({pct:+.1f}%) in FY2024."

    # Query 3: Cash Flow from Operations
    elif "cash flow" in query and "operating" in query and "microsoft" in query:
        val = df[(df['Company'] == 'Microsoft') & (df['Fiscal_Year'] == 'FY2025')]['Cash_Flow_Ops'].iloc[0]
        return f"Microsoft generated ${val:,} million in cash flow from operating activities in FY2025."

    # Default
    else:
        return ("Sorry, I can only answer specific predefined queries. Try:\n"
                "• 'What is Microsoft's total revenue?'\n"
                "• 'How has Tesla's net income changed?'\n"
                "• 'What is Apple's cash flow from operating activities?'")

# Interactive Loop
def run_chatbot():
    print("Financial Analysis Chatbot (Type 'quit' to exit)\n")
    while True:
        user_input = input("You: ")
        if user_input.lower() in ['quit', 'exit', 'bye']:
            print("Bot: Goodbye!")
            break
        response = simple_chatbot(user_input)
        print(f"Bot: {response}\n")

if __name__ == "__main__":
    run_chatbot()